/**
 * TasksServer API
 * API for managing users and tasks. Provides basic CRUD operations for both entities. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HealthzGet200Response from '../model/HealthzGet200Response';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the healthzGet operation.
     * @callback module:api/DefaultApi~healthzGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HealthzGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Health check
     * Simple liveness check. Returns 200 if service and DB are alive.
     * @param {module:api/DefaultApi~healthzGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HealthzGet200Response}
     */
    healthzGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HealthzGet200Response;
      return this.apiClient.callApi(
        '/healthz', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
