/**
 * TasksServer API
 * API for managing users and tasks. Provides basic CRUD operations for both entities. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HealthzGet200Response model module.
 * @module model/HealthzGet200Response
 * @version 1.0.0
 */
class HealthzGet200Response {
    /**
     * Constructs a new <code>HealthzGet200Response</code>.
     * @alias module:model/HealthzGet200Response
     */
    constructor() { 
        
        HealthzGet200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HealthzGet200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HealthzGet200Response} obj Optional instance to populate.
     * @return {module:model/HealthzGet200Response} The populated <code>HealthzGet200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HealthzGet200Response();

            if (data.hasOwnProperty('ok')) {
                obj['ok'] = ApiClient.convertToType(data['ok'], 'Boolean');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HealthzGet200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HealthzGet200Response</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} ok
 */
HealthzGet200Response.prototype['ok'] = undefined;

/**
 * @member {Date} time
 */
HealthzGet200Response.prototype['time'] = undefined;






export default HealthzGet200Response;

